### PR TITLE
Adding final Icons from Design team

### PR DESCRIPTION
**Pull request by bhakta-ibm**
### Description

Got the icons from the design team. 

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
@bhakta-ibm Can you update the `offering_icon_url` value in the `ibm_catalog.json` to point to the icon we want to show in the catalog? Lock into main branch URL so it will always show the latest

**Comment by bhakta-ibm** [comment]
> @bhakta-ibm Can you update the `offering_icon_url` value in the `ibm_catalog.json` to point to the icon we want to show in the catalog? Lock into main branch URL so it will always show the latest

Done

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
