### PR TITLE
Expose `en_email_list` variable and update VLs

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Expose `en_email_list` variable and update VLs

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [x] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by ocofaigh** [comment]
```
Error:      	Received unexpected error:
        	            	Get "https://projects.api.cloud.ibm.com/v1/projects/68e234d4-593c-47e7-9528-8626608c5d98/configs/2a6fbe5d-31ab-4fde-adf5-134ddeafe1cf": read tcp 172.18.0.2:52806->23.45.46.165:443: read: connection reset by peer
```

Unrelated to changes in this PR, so re-running

**Review by MatthewLemmond — DISMISSED** [review]

**Review by MatthewLemmond — APPROVED** [review]

**Review by MatthewLemmond — APPROVED** [review]

**Comment by ocofaigh** [comment]
Pipeline failed with:
```
 2024/06/19 20:10:59 Terraform apply |     "Result": {
 2024/06/19 20:10:59 Terraform apply |         "details": "{\"operation\":\"Provision\",\"description\":\"Sysdig provision request return code: 400 response: {\\\"errors\\\":[{\\\"reason\\\":\\\"Bad Request\\\",\\\"message\\\":\\\"The existing customerId 113063 is already connected.\\\"}]}\",\"dashboard_url\":\"https://cloud.ibm.com/workload-protection/0a1363b1-e059-4038-a9c2-ab37a0b7a164/overview\",\"default_consumer_instance\":false,\"public_service_endpoint_enabled\":false,\"api_token_auth_disabled\":false,\"extensions\":{\"external_dashboard\":\"https://us-south.security-compliance-secure.cloud.ibm.com/api/oauth/openid/IBM/abac0df06b644a9cabc6e44f55b3880e/0a1363b1-e059-4038-a9c2-ab37a0b7a164?serviceName=SYSDIG_SECURE\u0026product=SDS\"}}",
 2024/06/19 20:10:59 Terraform apply |         "error_code": "RC-ServiceBrokerErrorResponse",
 2024/06/19 20:10:59 Terraform apply |         "message": "Please contact the Service Provider for this error. [400, Bad Request] Sysdig provision request return code: 400 response: {\"errors\":[{\"reason\":\"Bad Request\",\"message\":\"The existing customerId 113063 is already connected.\"}]}",
 2024/06/19 20:10:59 Terraform apply |         "status_code": 422,
 2024/06/19 20:10:59 Terraform apply |         "transaction_id": "bss-35919462eb7dab2f"
 2024/06/19 20:10:59 Terraform apply |     },
 2024/06/19 20:10:59 Terraform apply |     "RawResult": null
 2024/06/19 20:10:59 Terraform apply | }
```

Reported to service team. Going to retry..

**Pull request merged**
