### PR TITLE
add architecuture diagram

### PR DESCRIPTION
**Pull request by bhakta-ibm**
### Release required?

- [X] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by ocofaigh — CHANGES_REQUESTED** [review]
This diagram needs to be cleaned up, however we can use it as a starting base. 
@bhakta-ibm can you move it into the `reference-architecture` directory please, and also reference it in the ibm_catalog.json ?

**Comment by bhakta-ibm** [comment]
Updated requested changes. We can do clean up with iterations.

**Comment by ocofaigh** [comment]
@bhakta-ibm You can remove all the other diagram links from the ibm_catalog.json - I believe catalog will automatically add those

**Comment by bhakta-ibm** [comment]
Removed.

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
